# NumPy

In [59]:
import numpy as np

In [60]:
np.__version__

'1.15.4'

In [61]:
np.  #enter np.[tab key] to see a list of all methods

SyntaxError: invalid syntax (<ipython-input-61-2bce4b981cdc>, line 1)

In [62]:
print(dir(np))
len(dir(np)) #numpy has 625 methods

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', '_mklinit', 'abs', 'absolute', 'ab

627

In [63]:
#numpy is used for array manipulation
# there is a builtin array module in python but it is not as efficient as numpy
# For any operations on array, numpy and pandas are the most useful

In [64]:
lst = [10,20,30,40]
arr1=np.array(lst)
print(type(arr1))
print(arr1.shape)
print(arr1.size)

<class 'numpy.ndarray'>
(4,)
4


In [65]:
lst = [[10,20,30,40],[100,200,300,400,500]]
print(lst)
arr1=np.array(lst)
print(type(arr1))
print(arr1.shape)
print(arr1.size)
arr1

[[10, 20, 30, 40], [100, 200, 300, 400, 500]]
<class 'numpy.ndarray'>
(2,)
2


array([list([10, 20, 30, 40]), list([100, 200, 300, 400, 500])],
      dtype=object)

In [66]:
lst = [[10,20,30,40],[100,200,300,400,500]]
print(lst)
arr1=np.array(lst)
print(type(arr1))
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)
print(arr1)
arr1

[[10, 20, 30, 40], [100, 200, 300, 400, 500]]
<class 'numpy.ndarray'>
(2,)
2
object
[list([10, 20, 30, 40]) list([100, 200, 300, 400, 500])]


array([list([10, 20, 30, 40]), list([100, 200, 300, 400, 500])],
      dtype=object)

# 1D Array

In [70]:
arr1 = np.arange(5) # this is a 1D array
arr1

array([0, 1, 2, 3, 4])

In [71]:
print(arr1) # if you print arr1 (array object) it will show as a list but it is actually an array

[0 1 2 3 4]


In [72]:
arr2 = np.arange(5).reshape(2,3) # not possible since there are only 5 elements and we are reshaping to 6 elements
arr2

ValueError: cannot reshape array of size 5 into shape (2,3)

# 2d Array

In [76]:
arr2 = np.arange(6).reshape(2,3) # This is a 2d array
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
print(arr2)

[[0 1 2]
 [3 4 5]]


In [74]:
lst = [[10,20,30],[100,200,300]] # This is a 2d list
lst
#Difference between 2D list and 2D array is the way it prints the elements

[[10, 20, 30], [100, 200, 300]]

# 3D Array

In [ ]:
arr3 = np.arange(18).reshape(3,3,3) # This is a 3d array
arr3

In [79]:
arr3 = np.arange(18).reshape(3,3,2) # This is a 3d array
arr3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [80]:
print(arr3)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [81]:
#Creating an array of large values
#while print the middle values will not be printed
arr4 =np.arange(3000)
arr4

array([   0,    1,    2, ..., 2997, 2998, 2999])

In [82]:
arr5 =np.arange(10000).reshape(500,20) #Notice how it is getting printed
arr5

array([[   0,    1,    2, ...,   17,   18,   19],
       [  20,   21,   22, ...,   37,   38,   39],
       [  40,   41,   42, ...,   57,   58,   59],
       ...,
       [9940, 9941, 9942, ..., 9957, 9958, 9959],
       [9960, 9961, 9962, ..., 9977, 9978, 9979],
       [9980, 9981, 9982, ..., 9997, 9998, 9999]])

In [83]:
#to change options in print
import sys 
np.set_printoptions(threshold = sys.maxsize)
print(arr5) #after changing print options to maxsize all values are printed

[[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
    14   15   16   17   18   19]
 [  20   21   22   23   24   25   26   27   28   29   30   31   32   33
    34   35   36   37   38   39]
 [  40   41   42   43   44   45   46   47   48   49   50   51   52   53
    54   55   56   57   58   59]
 [  60   61   62   63   64   65   66   67   68   69   70   71   72   73
    74   75   76   77   78   79]
 [  80   81   82   83   84   85   86   87   88   89   90   91   92   93
    94   95   96   97   98   99]
 [ 100  101  102  103  104  105  106  107  108  109  110  111  112  113
   114  115  116  117  118  119]
 [ 120  121  122  123  124  125  126  127  128  129  130  131  132  133
   134  135  136  137  138  139]
 [ 140  141  142  143  144  145  146  147  148  149  150  151  152  153
   154  155  156  157  158  159]
 [ 160  161  162  163  164  165  166  167  168  169  170  171  172  173
   174  175  176  177  178  179]
 [ 180  181  182  183  184  185  186  187  188  189  19

# Reshaping

In [89]:
a=np.arange(6)
a2=a.reshape(2,3)
print(a)
print(a2)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [96]:
state_arr = np.array(['UP','AP','AA','TN','DL','WB','RJ','MH'])
state_arr

array(['UP', 'AP', 'AA', 'TN', 'DL', 'WB', 'RJ', 'MH'], dtype='<U2')

In [97]:
state_arr.reshape(-1,4) #-1

array([['UP', 'AP', 'AA', 'TN'],
       ['DL', 'WB', 'RJ', 'MH']], dtype='<U2')

In [98]:
state_arr.reshape(4,-1) #-1

array([['UP', 'AP'],
       ['AA', 'TN'],
       ['DL', 'WB'],
       ['RJ', 'MH']], dtype='<U2')

In [99]:
len(state_arr)

8

# Structured Arrays in NumPy

In [12]:
import numpy as np

In [13]:
e_name = ['ABC', 'XYZ', 'MNO','PQR']

e_id = [101, 102, 103, 104]

e_sal = [10000.00, 14543.45, 32244.45, 80000.00]

In [14]:
emp_data = np.zeros(4, dtype={'names':('name', 'id', 'sal'), 'formats' : ('U10','i4','f8')})
emp_data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('id', '<i4'), ('sal', '<f8')])

In [15]:
emp_data.dtype

dtype([('name', '<U10'), ('id', '<i4'), ('sal', '<f8')])

In [16]:
emp_data['name'] = e_name
emp_data['id'] = e_id
emp_data['sal'] = e_sal

In [17]:
print(emp_data)

[('ABC', 101, 10000.  ) ('XYZ', 102, 14543.45) ('MNO', 103, 32244.45)
 ('PQR', 104, 80000.  )]


In [18]:
emp_data['name']

array(['ABC', 'XYZ', 'MNO', 'PQR'], dtype='<U10')

In [19]:
emp_data['id']

array([101, 102, 103, 104], dtype=int32)

In [20]:
emp_data['sal']

array([10000.  , 14543.45, 32244.45, 80000.  ])

In [21]:
emp_data[1]

('XYZ', 102, 14543.45)

In [22]:
emp_data[1]['name']

'XYZ'

# Broadcasting

In [23]:
import numpy as np

In [24]:
arr1 = np.arange(10,13)
print(arr1)

[10 11 12]


In [25]:
arr1+100 #100 is a scalar quantity and is broadcasted across the rows

array([110, 111, 112])

In [26]:
arr2 = np.arange(8).reshape(4,2)

In [27]:
print(arr2+200) #200 is a scalar quantity and is broadcasted across the rows and columns here

[[200 201]
 [202 203]
 [204 205]
 [206 207]]


# Row wise Broadcasting

In [36]:
arr1 = np.arange(10,13)
arr1

array([10, 11, 12])

In [37]:
arr3 = np.arange(200,206).reshape(2,3)
arr3

array([[200, 201, 202],
       [203, 204, 205]])

In [38]:
arr1+arr3 

array([[210, 212, 214],
       [213, 215, 217]])

# Column Wise Broadcasting

In [39]:
arr1

array([10, 11, 12])

In [41]:
arr4 = np.arange(200,202).reshape(2,1)
arr4

array([[200],
       [201]])

In [42]:
arr1+arr4

array([[210, 211, 212],
       [211, 212, 213]])

In [ ]:
#Same concept applies for Multiplication, Division etc.

# Broadcasting done in both directions

In [44]:
a = np.array([0,3]).reshape(2,1)
a

array([[0],
       [3]])

In [46]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [47]:
a+b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# [0 0 0] [0 1 2]
# [3 3 3] [0 1 2] # now add element by element

# Splitting an array

In [ ]:
impor numpy as np

In [51]:
arr1 = np.arange(100,118)
arr1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117])

In [54]:
#splitting an array into 6 equal sized array
arr2=np.split(arr1,(6,3))
arr2

[array([100, 101, 102, 103, 104, 105]),
 array([], dtype=int64),
 array([103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117])]

# Views

# Image Manipulation

In [55]:
import numpy as np

In [57]:
from skimage import data

In [58]:
astronaut = data.astronaut()